### ISSUE TITLE
Documentation mismatch for `ConvertPar`

### ISSUE THREAD

**Issue by AlexisDerumigny** [mlysy/LocalCop#15]
Hi @EFAcar, I am checking the code in the `ConvertPar.R` file and it seems that the range of families mentioned in the documentation does not match the one actually implemented. The documentation says:

https://github.com/mlysy/LocalCop/blob/c9f16c287b87e5a4ea0bc8ddf93386cdb631d06e/R/ConvertPar.R#L19-L26

but it seems to me that a lot more families are actually implemented in the same file below (maybe all of them, in fact).
It could be nice to mention this in the documentation too.

https://github.com/openjournals/joss-reviews/issues/6744

**Comment by AlexisDerumigny** [comment]
After reading more, I have the impression that this is because the rest of the code is not compatible with families outside 1-5.

Would you think it would be a lot of work to implement also the other families? In particular, I have the impression that adding the rotated ones would be quite similar to the existing code.

(corresponding to the idea "JOSS requires that software should be feature-complete", see https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort )

**Comment by mlysy** [comment]
Thanks @AlexisDerumigny, we've added the rotated versions of applicable copulas within families 1-5 in #18.
