### ISSUE TITLE
Community Guideline

### ISSUE THREAD

**Issue by mingzehuang** [mlysy/LocalCop#7]
Hi, @EFAcar , is there a community guideline about contributions? Since the review checklist has the requirement as follow:
"Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"
[openjournals/joss-reviews#6744](https://github.com/openjournals/joss-reviews/issues/6744)

**Comment by EFAcar** [comment]
Hi @mingzehuang, the `DESCRIPTION` file has a `BugReports` section linking to the issue tracker.  In addition, we added a Contributions section to the README. Please let us know if you'd like us to do add anything else for this.

**Comment by mingzehuang** [comment]
Great, thanks @EFAcar!
